version: 2
jobs:
  build:
    docker:
      - image: ifunky/polydev:latest
    working_directory: ~/terraform
    steps:
      - checkout:
          path: ~/terraform
      - run:
          name: Validate
          command: make polydev/validate
